.TH "CUfileError" 3 "Wed Feb 12 2025" "GPUDirect Storage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CUfileError \- cufileop status string  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cufile\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "CUresult \fBcu_err\fP"
.br
.ti -1c
.RI "\fBCUfileOpError\fP \fBerr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
cufileop status string 
.SH "Field Documentation"
.PP 
.SS "CUresult CUfileError::cu_err"

.SS "\fBCUfileOpError\fP CUfileError::err"


.SH "Author"
.PP 
Generated automatically by Doxygen for GPUDirect Storage from the source code\&.
