.TH "CUfileIOEvents" 3 "Wed Feb 12 2025" "GPUDirect Storage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CUfileIOEvents
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cufile\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBcookie\fP"
.br
.ti -1c
.RI "size_t \fBret\fP"
.br
.ti -1c
.RI "\fBCUfileStatus_t\fP \fBstatus\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* CUfileIOEvents::cookie"

.SS "size_t CUfileIOEvents::ret"

.SS "\fBCUfileStatus_t\fP CUfileIOEvents::status"


.SH "Author"
.PP 
Generated automatically by Doxygen for GPUDirect Storage from the source code\&.
