.TH "cufileRDMAInfo" 3 "Wed Feb 12 2025" "GPUDirect Storage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cufileRDMAInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cufile\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdesc_len\fP"
.br
.ti -1c
.RI "const char * \fBdesc_str\fP"
.br
.ti -1c
.RI "int \fBversion\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int cufileRDMAInfo::desc_len"

.SS "const char* cufileRDMAInfo::desc_str"

.SS "int cufileRDMAInfo::version"


.SH "Author"
.PP 
Generated automatically by Doxygen for GPUDirect Storage from the source code\&.
